markdown:    kramdown
highlighter: rouge
permalink:   pretty

port:        4000
url:         lucasgruwez.github.io
baseurl:     /lunar-icons

version:     v1.0.1
gzip:        4kb
icons:       150+

cdn:         https://unpkg.com/lunar-icons
repo:        https://github.com/lucasgruwez/lunar-icons
npm:         https://npmjs.org/packages/lunar-icons
author:      https://github.com/lucasgruwez







